n = int(input('Uma distancia em metros: '))
print('A medida de {} corresponde a: ')
print('{}km'.format(n/1000))
print('{}hm'.format(n/100))
print('{}dam'.format(n/10))
print('{}dm'.format(n*10))
print('{}cm'.format(n*100))
print('{}mm'.format(n*1000))
