I = 1
IV = 4
V = 5
IX = 9
X = 10
L = 50
C = 100
D = 500
M = 1000
n = int(input())
resposta = ''
while n > 0:
    if n >= M:
        n -= M
        resposta += 'M'
    elif n >= (M-C):
        n -= (M-C)
        resposta += 'CM'
    elif n >= D:
        n -= D
        resposta += 'D'
    elif n >= D-C:
        n -= (D-C)
        resposta += 'CD'
    elif n >= C:
        n -= C
        resposta += 'C'
    elif n >= (C-X):
        n -= (C-X)
        resposta += 'XC'
    elif n >= L:
        n -= L
        resposta += 'L'
    elif n >= (L-X):
        n -= (L-X)
        resposta += 'XL'
    elif n >= X:
        n -= X
        resposta += 'X'
    elif n >= (X-I):
        n -= (X-I)
        resposta += 'IX'
    elif n >= V:
        n -= V
        resposta += 'V'
    elif n >= (V-I):
        n -= (V-I)
        resposta += 'IV'
    elif n >= I:
        n -= I
        resposta += 'I'
print(resposta)
